version: '3.9'

services:
  docker-dind:
    image: docker:20.10-dind
    container_name: docker-dind
    privileged: true
    environment:
      - DOCKER_TLS_CERTDIR=
    ports:
      - "2375:2375" # Expose Docker daemon without TLS (for simplicity on local)
    volumes:
      - dind-data:/var/lib/docker
    restart: unless-stopped

  jenkins:
    image: jenkins/jenkins:lts
    container_name: socila-media-jenkins
    user: root
    ports:
      - "9090:8080"
      - "50000:50000"
    environment:
      - DOCKER_HOST=tcp://docker-dind:2375
    depends_on:
      - docker-dind
    volumes:
      - jenkins_home:/var/jenkins_home
      - /usr/bin/docker:/usr/bin/docker # Mount docker binary
    networks:
      - app-network
    restart: unless-stopped

  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network
    restart: unless-stopped

  app:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: socila-media-app
    ports:
      - "4001:4000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    depends_on:
      - mongo
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  jenkins_home:
  mongodb_data:
  dind-data:
