version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "4001:4000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    depends_on:
      - mongo
    networks:
      - app-network
    restart: unless-stopped

  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network
    restart: unless-stopped

  docker:
    image: docker:20.10-dind
    container_name: docker-dind
    privileged: true
    environment:
      - DOCKER_TLS_CERTDIR=
    ports:
      - "2375:2375"  # Jenkins will connect here
    networks:
      - app-network
    restart: unless-stopped

  jenkins:
    image: jenkins/jenkins:lts
    container_name: socila-media-jenkins-1
    user: root
    ports:
      - "9090:8080"
      - "50000:50000"
    environment:
      DOCKER_HOST: tcp://docker:2375
    depends_on:
      - docker
    networks:
      - app-network
    volumes:
      - jenkins_home:/var/jenkins_home
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data:
  jenkins_home:
